# Generated by Django 5.2.7 on 2025-11-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', help_text='Avatar do usuário', null=True, upload_to='avatars/'),
        ),
    ]
