# Generated by Django 5.2.7 on 2025-10-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nascimento',
        ),
    ]
