# Generated by Django 5.2.7 on 2025-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='descrição da anotação', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Concluido'), (2, 'Fazendo'), (3, 'Pendente')], default=3)),
            ],
        ),
    ]
