# Generated by Django 5.2.7 on 2025-11-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notas",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
