# Generated by Django 5.2.7 on 2025-11-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0003_notas_data_atualizacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notas",
            name="data_atualizacao",
        ),
    ]
