ERROR_404 = "Anotação não localizada."
ERROR_PERMISSION_DENIED = "Você não tem permissão para editar este usuário."
ERROR_CREATE_OR_EMAIL = "Erro ao criar nota ou agendar e-mail."
KEY_ERROR = "error"
USER_LOCALIZATION = "Usuário não localizado"
RESULT_RESPONSE = "result"
